language: rvm
rvm:
  - 2.0.0
install:
  - gem install jekyll -V
  - gem install rdiscount -V
before_script:
  - git submodule update --init -v 
  - git submodule foreach git pull origin master -v
script:
  - jekyll -v
  - jekyll build -V
